// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ-b-mnW_N21e3VNdRUJRxDU2-7soEetk',
    appId: '1:470334581939:web:3269b0d9264abda784d4c6',
    messagingSenderId: '470334581939',
    projectId: 'ai-personal-manager-e193e',
    authDomain: 'ai-personal-manager-e193e.firebaseapp.com',
    storageBucket: 'ai-personal-manager-e193e.firebasestorage.app',
    measurementId: 'G-9704T4M5Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1rwwWN16nXPTZtQLfLk4FCyXqXA59Mw',
    appId: '1:470334581939:android:5b6f4d609917b95e84d4c6',
    messagingSenderId: '470334581939',
    projectId: 'ai-personal-manager-e193e',
    storageBucket: 'ai-personal-manager-e193e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEXde1nMmI0BV-lJuly9vfzOwfr7YlXFw',
    appId: '1:470334581939:ios:5237649c61ae31fe84d4c6',
    messagingSenderId: '470334581939',
    projectId: 'ai-personal-manager-e193e',
    storageBucket: 'ai-personal-manager-e193e.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEXde1nMmI0BV-lJuly9vfzOwfr7YlXFw',
    appId: '1:470334581939:ios:5237649c61ae31fe84d4c6',
    messagingSenderId: '470334581939',
    projectId: 'ai-personal-manager-e193e',
    storageBucket: 'ai-personal-manager-e193e.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ-b-mnW_N21e3VNdRUJRxDU2-7soEetk',
    appId: '1:470334581939:web:24bd59b772060d9584d4c6',
    messagingSenderId: '470334581939',
    projectId: 'ai-personal-manager-e193e',
    authDomain: 'ai-personal-manager-e193e.firebaseapp.com',
    storageBucket: 'ai-personal-manager-e193e.firebasestorage.app',
    measurementId: 'G-S97EGG5RE1',
  );
}
